-- One authoritative credit policy for the desktop client, gateway, and DB.
-- The gateway may display a quote, but this migration is the final authority
-- for reservations and settlement. A reservation is only charged after the
-- generated bytes have been durably stored for the requesting user.

create or replace function public.quote_minimax_h3_video_retail_credits(
  p_resolution text,
  p_output_seconds integer,
  p_input_seconds integer default 0,
  p_input_image_count integer default 0
)
returns integer
language sql
immutable
set search_path = public
as $$
  select (
    ceil(
      (case when upper(trim(coalesce(p_resolution, ''))) = '2K'
        then 0.1825 else 0.1125 end)
      * 7.3 * (1000.0 / 70.0) * 1.10 / 0.80
    )
    * greatest(0, coalesce(p_output_seconds, 0) + coalesce(p_input_seconds, 0))
    + ceil(0.055 * 7.3 * (1000.0 / 70.0) * 1.10 / 0.80)
      * greatest(0, coalesce(p_input_image_count, 0) - 5)
  )::integer
$$;

create or replace function public.quote_ai_image_unit_credits(
  p_provider_id text,
  p_resolution text default null
)
returns integer
language plpgsql
immutable
set search_path = public
as $$
declare
  provider_id text := lower(trim(coalesce(p_provider_id, '')));
  supplied_resolution text := lower(trim(coalesce(p_resolution, '')));
  quality text;
  image_resolution text;
  upstream_points numeric;
begin
  if provider_id in ('image-6', 'atlas-image-gpt2', 'atlas-image-gpt2-edit') then
    quality := split_part(supplied_resolution || ':1k', ':', 1);
    image_resolution := split_part(supplied_resolution || ':1k', ':', 2);
    if quality not in ('low', 'medium', 'high', 'auto') then quality := 'auto'; end if;
    if image_resolution not in ('1k', '2k', '4k') then image_resolution := '1k'; end if;
    upstream_points := case
      when provider_id = 'atlas-image-gpt2' then case quality
        when 'low' then case image_resolution when '1k' then 1 else 2 end
        when 'high' then case image_resolution when '1k' then 16 else 32 end
        else case image_resolution when '1k' then 5 else 9 end
      end
      else case quality
        when 'low' then case image_resolution when '1k' then 2 else 3 end
        when 'high' then case image_resolution when '1k' then 17 else 33 end
        else case image_resolution when '1k' then 6 else 10 end
      end
    end;
    return public.quote_retail_credits_from_upstream_points(upstream_points);
  end if;

  if provider_id = 'image-3' then
    return case when supplied_resolution = '4k' then 8 else 5 end;
  end if;

  upstream_points := case provider_id
    when 'image-1' then case supplied_resolution
      when '1k' then 0.14 * 7.3 * (1000.0 / 70.0)
      when '4k' then 0.48 * 7.3 * (1000.0 / 70.0)
      else 0.24 * 7.3 * (1000.0 / 70.0) end
    when 'image-2' then case supplied_resolution
      when '1k' then 4 when '4k' then 8 else 6 end
    when 'image-4' then 2
    when 'image-5' then 2
    when 'image-7' then case when supplied_resolution = '1080p' then 4 else 2 end
    when 'image-8' then case when supplied_resolution = '1080p' then 4 else 2 end
    when 'image-9' then 3
    when 'image-10' then case when supplied_resolution = '4k' then 7 else 4 end
    when 'image-11' then case when supplied_resolution = '4k' then 4 else 3 end
    when 'image-12' then case supplied_resolution when '2k' then 3 when '4k' then 4 else 2 end
    when 'image-13' then 2
    when 'image-14' then 2
    when 'image-15' then case when supplied_resolution = '2k' then 4 else 3 end
    when 'image-16' then 2
    when 'image-17' then case when supplied_resolution = '2k' then 0.32 * 7.3 * (1000.0 / 70.0) else 0.08 * 7.3 * (1000.0 / 70.0) end
    when 'image-18' then case when supplied_resolution = '2k' then 0.32 * 7.3 * (1000.0 / 70.0) else 0.08 * 7.3 * (1000.0 / 70.0) end
    else null
  end;
  if upstream_points is null then return null; end if;
  return public.quote_retail_credits_from_upstream_points(upstream_points);
end;
$$;

create or replace function public.reserve_ai_media_credits(
  p_user_id uuid,
  p_kind text,
  p_provider_id text,
  p_request_id uuid,
  p_resolution text default null,
  p_duration integer default null,
  p_expected_credits integer default null,
  p_count integer default 1
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_kind text := lower(trim(coalesce(p_kind, '')));
  normalized_provider text := lower(trim(coalesce(p_provider_id, '')));
  normalized_resolution text := lower(trim(coalesce(p_resolution, '')));
  count_to_generate integer := greatest(1, least(4, coalesce(p_count, 1)));
  unit_credits integer;
begin
  if normalized_kind <> 'image' then
    return jsonb_build_object('ok', false, 'reason', 'provider-not-allowed');
  end if;
  unit_credits := public.quote_ai_image_unit_credits(normalized_provider, normalized_resolution);
  if unit_credits is null then
    return jsonb_build_object('ok', false, 'reason', 'provider-not-allowed');
  end if;
  return public.reserve_priced_ai_credits_internal(
    p_user_id, normalized_kind, normalized_provider, p_request_id,
    normalized_resolution, null, p_expected_credits, unit_credits * count_to_generate
  );
end;
$$;

create or replace function public.quote_ai_video_retail_credits(
  p_provider_id text,
  p_resolution text default null,
  p_duration integer default 6,
  p_reference_image_count integer default 0,
  p_has_reference_video boolean default false
)
returns integer
language plpgsql
immutable
set search_path = public
as $$
declare
  provider_id text := lower(trim(coalesce(p_provider_id, '')));
  resolution text := upper(trim(coalesce(p_resolution, '')));
  duration integer;
  rate_per_second numeric;
  minimum_upstream_points numeric := 0;
  reference_images integer := greatest(0, coalesce(p_reference_image_count, 0));
begin
  if provider_id = 'video-1' then
    duration := case when coalesce(p_duration, 6) = -1 then 15
      else greatest(4, least(15, coalesce(p_duration, 6))) end;
    return public.quote_minimax_h3_video_retail_credits(
      case when resolution = '2K' then '2K' else '768P' end,
      duration,
      case when coalesce(p_has_reference_video, false) then 15 else 0 end,
      reference_images
    );
  end if;

  if provider_id in ('video-2', 'atlas-video-seedance20-i2v', 'atlas-video-seedance20-ref') then
    duration := case when coalesce(p_duration, 6) = -1 then 15
      else greatest(4, least(15, coalesce(p_duration, 6))) end;
    rate_per_second := case resolution
      when '480P' then 8.268929 when '720P-SR' then 14.88408
      when '1080P' then 40.0113 when '1080P-SR' then 32.00904
      when '1440P-SR' then 56.90496 when '4K' then 91.225764
      else 17.7828 end;
  elsif provider_id in ('video-3', 'atlas-video-seedance25-i2v', 'atlas-video-seedance25-ref') then
    duration := case when coalesce(p_duration, 6) = -1 then 30
      else greatest(4, least(30, coalesce(p_duration, 6))) end;
    rate_per_second := case resolution
      when '480P' then 10.269725 when '720P-SR' then 16.123462
      when '720P-ESR' then 18.485498 when '1080P' then 43.469408
      when '1080P-SR' then 29.815561 when '1080P-ESR' then 33.128398
      when '1080P-ESR & 60FPS' then 36.441248 when '1440P-SR' then 51.454793
      when '1440P-ESR' then 55.876573 when '4K-ESR' then 168.756088739
      else 22.1160654 end;
    if resolution = '4K-ESR' then minimum_upstream_points := 1687.56088739; end if;
  elsif provider_id = 'video-4' then
    duration := case when coalesce(p_duration, 6) = -1 then 15
      else greatest(4, least(15, coalesce(p_duration, 6))) end;
    rate_per_second := case resolution when '480P' then 6.16465728
      when '720P' then 12.32931456 else null end;
  elsif provider_id = 'video-5' then
    duration := greatest(2, least(12, coalesce(p_duration, 6)));
    rate_per_second := case when resolution = '480P' then 2 else 3 end;
  elsif provider_id = 'video-6' then
    duration := greatest(2, least(12, coalesce(p_duration, 6)));
    rate_per_second := case resolution when '480P' then 2 when '720P' then 3 else 4 end;
  elsif provider_id = 'video-7' then
    duration := greatest(2, least(12, coalesce(p_duration, 6)));
    rate_per_second := case when resolution = '480P' then 1.5 else 2.5 end;
  elsif provider_id = 'video-8' then
    duration := greatest(5, least(10, coalesce(p_duration, 6)));
    rate_per_second := case when resolution = '1080P' then 1 else 0.5 end;
  elsif provider_id = 'video-9' then
    duration := greatest(5, least(10, coalesce(p_duration, 6)));
    rate_per_second := 2;
  elsif provider_id = 'video-10' then
    duration := greatest(3, least(15, coalesce(p_duration, 5)));
    rate_per_second := 18.4;
  elsif provider_id = 'video-11' then
    duration := greatest(3, least(15, coalesce(p_duration, 5)));
    rate_per_second := 24.6;
  elsif provider_id = 'video-12' then
    duration := greatest(3, least(15, coalesce(p_duration, 5)));
    rate_per_second := 21.9;
  elsif provider_id = 'video-13' then
    duration := greatest(3, least(15, coalesce(p_duration, 5)));
    rate_per_second := 26.3;
  else
    return null;
  end if;
  if rate_per_second is null then return null; end if;
  return public.quote_video_retail_credits_from_upstream_points(
    greatest(rate_per_second * duration, minimum_upstream_points)
  );
end;
$$;

create or replace function public.reserve_ai_video_credits(
  p_user_id uuid,
  p_kind text,
  p_provider_id text,
  p_request_id uuid,
  p_resolution text default null,
  p_duration integer default null,
  p_expected_credits integer default null,
  p_reference_image_count integer default 0,
  p_has_reference_video boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_provider text := lower(trim(coalesce(p_provider_id, '')));
  quoted_credits integer;
begin
  if lower(trim(coalesce(p_kind, ''))) <> 'video' then
    return jsonb_build_object('ok', false, 'reason', 'provider-not-allowed');
  end if;
  quoted_credits := public.quote_ai_video_retail_credits(
    normalized_provider, p_resolution, p_duration,
    p_reference_image_count, p_has_reference_video
  );
  if quoted_credits is null then
    return jsonb_build_object('ok', false, 'reason', 'provider-not-allowed');
  end if;
  -- The gateway may include a conservative reference-media reserve that is
  -- not available in the legacy async job signature. Never lower it; an
  -- overestimate is released or settled by the normal idempotent flow.
  if p_expected_credits is not null and p_expected_credits > quoted_credits then
    return public.reserve_priced_ai_credits_internal(
      p_user_id, 'video', normalized_provider, p_request_id,
      upper(trim(coalesce(p_resolution, ''))), p_duration,
      p_expected_credits, p_expected_credits
    );
  end if;
  return public.reserve_priced_ai_credits_internal(
    p_user_id, 'video', normalized_provider, p_request_id,
    upper(trim(coalesce(p_resolution, ''))), p_duration,
    p_expected_credits, quoted_credits
  );
end;
$$;

create or replace function public.reserve_minimax_video_credits(
  p_user_id uuid,
  p_request_id uuid,
  p_resolution text,
  p_duration integer,
  p_expected_credits integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_resolution text := case when upper(trim(coalesce(p_resolution, ''))) = '2K' then '2K' else '768P' end;
  normalized_duration integer := case when coalesce(p_duration, 6) = -1 then 15
    else greatest(4, least(15, coalesce(p_duration, 6))) end;
  minimum_credits integer;
begin
  minimum_credits := public.quote_minimax_h3_video_retail_credits(
    normalized_resolution, normalized_duration, 0, 0
  );
  -- A reference video or more than five reference images can increase the
  -- gateway's conservative reservation. Never silently lower that ceiling.
  if p_expected_credits is null or p_expected_credits < minimum_credits then
    return jsonb_build_object('ok', false, 'reason', 'pricing-mismatch', 'credits', minimum_credits);
  end if;
  return public.reserve_priced_ai_credits_internal(
    p_user_id, 'video', 'video-1', p_request_id,
    normalized_resolution, normalized_duration, p_expected_credits, p_expected_credits
  );
end;
$$;

create or replace function public.start_ai_video_job(
  p_request_id uuid, p_user_id uuid, p_token_hash text, p_request_hash text,
  p_provider_id text, p_resolution text, p_duration integer,
  p_aspect_ratio text, p_expected_credits integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_job public.ai_video_jobs%rowtype;
  reservation jsonb;
  normalized_provider text := lower(trim(coalesce(p_provider_id, '')));
begin
  if lower(trim(coalesce(p_token_hash, ''))) !~ '^[0-9a-f]{64}$'
     or lower(trim(coalesce(p_request_hash, ''))) !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('ok', false, 'reason', 'invalid-job-hash');
  end if;
  select * into existing_job from public.ai_video_jobs where request_id = p_request_id for update;
  if found then
    if existing_job.user_id <> p_user_id
       or existing_job.token_hash <> lower(trim(p_token_hash))
       or existing_job.request_hash <> lower(trim(p_request_hash))
       or existing_job.provider_id <> normalized_provider then
      return jsonb_build_object('ok', false, 'reason', 'request-id-conflict');
    end if;
    return jsonb_build_object('ok', true, 'reason', 'already-started',
      'requestId', existing_job.request_id, 'status', existing_job.status,
      'credits', existing_job.credits_reserved, 'createdAt', existing_job.created_at,
      'deadlineAt', existing_job.deadline_at);
  end if;

  reservation := public.reserve_ai_video_credits(
    p_user_id, 'video', normalized_provider, p_request_id, p_resolution, p_duration,
    p_expected_credits, 0, false
  );
  if coalesce((reservation->>'ok')::boolean, false) is not true then return reservation; end if;

  insert into public.ai_video_jobs (
    request_id, user_id, token_hash, request_hash, provider_id,
    resolution, duration_seconds, aspect_ratio, credits_reserved
  ) values (
    p_request_id, p_user_id, lower(trim(p_token_hash)), lower(trim(p_request_hash)),
    normalized_provider, upper(trim(p_resolution)), p_duration,
    trim(p_aspect_ratio), coalesce((reservation->>'credits')::integer, 0)
  ) returning * into existing_job;
  return reservation || jsonb_build_object(
    'requestId', existing_job.request_id, 'status', existing_job.status,
    'createdAt', existing_job.created_at, 'deadlineAt', existing_job.deadline_at
  );
end;
$$;

alter function public.current_policy_ai_usage_credits(uuid, text, text, text, integer)
  rename to current_policy_ai_usage_credits_legacy_202609030001;

create or replace function public.current_policy_ai_usage_credits(
  p_request_id uuid,
  p_kind text,
  p_provider_id text,
  p_resolution text,
  p_duration integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.ai_video_jobs%rowtype;
  output_seconds integer;
  input_seconds integer;
  image_count integer;
begin
  if lower(trim(coalesce(p_kind, ''))) <> 'video' then
    return public.current_policy_ai_usage_credits_legacy_202609030001(
      p_request_id, p_kind, p_provider_id, p_resolution, p_duration
    );
  end if;

  select * into job from public.ai_video_jobs where request_id = p_request_id;
  output_seconds := greatest(0, coalesce(job.provider_output_seconds, job.duration_seconds, p_duration, 6));
  input_seconds := greatest(0, coalesce(job.provider_input_seconds, 0));
  image_count := greatest(0, coalesce(job.provider_input_image_count, 0));
  if job.provider_output_seconds is null and job.provider_input_seconds is null
     and job.provider_total_seconds is not null then
    output_seconds := greatest(0, job.provider_total_seconds);
    input_seconds := 0;
  end if;
  return public.quote_ai_video_retail_credits(
    coalesce(nullif(job.provider_id, ''), lower(trim(coalesce(p_provider_id, '')))),
    coalesce(nullif(job.resolution, ''), nullif(p_resolution, ''), '768P'),
    output_seconds, image_count, input_seconds > 0
  );
end;
$$;

create or replace function public.settle_ai_video_download(
  p_user_id uuid,
  p_token_hash text,
  p_result_content_type text,
  p_result_bytes bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  job public.ai_video_jobs%rowtype;
  usage_record public.ai_usage%rowtype;
  account_record public.ai_credit_accounts%rowtype;
  settlement jsonb;
  output_seconds integer;
  input_seconds integer;
  image_count integer;
  target_credits integer;
  actual_retail_credits integer;
  top_up integer;
begin
  select * into job from public.ai_video_jobs
  where user_id = p_user_id
    and token_hash = lower(trim(coalesce(p_token_hash, '')))
  for update;
  if not found then return jsonb_build_object('ok', false, 'reason', 'not-found'); end if;
  if job.status = 'succeeded' then
    return jsonb_build_object('ok', true, 'reason', 'already-settled', 'status', job.status,
      'creditsEstimated', job.credits_reserved,
      'creditsCharged', coalesce(job.credits_charged, job.credits_reserved));
  end if;
  if job.status <> 'ready' then
    return jsonb_build_object('ok', false, 'reason', 'not-ready', 'status', job.status);
  end if;

  select * into account_record from public.ai_credit_accounts where user_id = p_user_id for update;
  select * into usage_record from public.ai_usage where request_id = job.request_id for update;
  if not found or usage_record.status <> 'reserved' then
    return jsonb_build_object('ok', false, 'reason', 'usage-not-reserved');
  end if;

  target_credits := usage_record.credits_reserved;
  if job.provider_id is not null then
    output_seconds := greatest(0, coalesce(job.provider_output_seconds, job.duration_seconds));
    input_seconds := greatest(0, coalesce(job.provider_input_seconds, 0));
    image_count := greatest(0, coalesce(job.provider_input_image_count, 0));
    if job.provider_output_seconds is null and job.provider_input_seconds is null
       and job.provider_total_seconds is not null then
      output_seconds := greatest(0, job.provider_total_seconds);
      input_seconds := 0;
    end if;
    actual_retail_credits := public.quote_ai_video_retail_credits(
      job.provider_id, job.resolution, output_seconds,
      image_count, input_seconds > 0
    );
    if actual_retail_credits is not null then
      target_credits := greatest(target_credits, actual_retail_credits);
    end if;
  end if;

  top_up := greatest(0, target_credits - usage_record.credits_reserved);
  if top_up > 0 then
    -- Keep the durable result and original reservation available. Releasing it
    -- here would discard a completed file and make a retry impossible.
    if account_record.balance - account_record.reserved < top_up then
      return jsonb_build_object('ok', false, 'reason', 'insufficient-credits', 'status', 'ready',
        'creditsEstimated', job.credits_reserved, 'creditsCharged', 0,
        'creditsHeld', usage_record.credits_reserved, 'creditsRequired', target_credits);
    end if;
    update public.ai_credit_accounts
    set reserved = reserved + top_up, updated_at = now()
    where user_id = p_user_id returning * into account_record;
    update public.ai_usage
    set credits_reserved = credits_reserved + top_up
    where request_id = job.request_id returning * into usage_record;
    update public.ai_video_jobs
    set credits_reserved = target_credits, updated_at = now()
    where request_id = job.request_id returning * into job;
    insert into public.ai_credit_ledger (
      user_id, event_type, balance_delta, reserved_delta, balance_after, reserved_after,
      request_id, reference_id, idempotency_key, metadata
    ) values (
      p_user_id, 'reserve', 0, top_up, account_record.balance, account_record.reserved,
      job.request_id, job.request_id::text, 'video-topup:' || job.request_id::text,
      jsonb_build_object('kind', 'video', 'providerId', job.provider_id, 'actualRetailCredits', target_credits)
    ) on conflict (user_id, idempotency_key) do nothing;
  end if;

  settlement := public.settle_ai_credits(
    job.request_id, 'succeeded', coalesce(job.provider_duration_ms, 0)
  );
  if coalesce((settlement->>'ok')::boolean, false) is not true
     or coalesce(settlement->>'status', '') <> 'succeeded' then
    raise exception using errcode = 'P0001', message = 'video credit settlement failed';
  end if;
  update public.ai_video_jobs
  set status = 'succeeded',
      result_content_type = nullif(left(trim(coalesce(p_result_content_type, 'video/mp4')), 128), ''),
      result_bytes = greatest(0, p_result_bytes),
      credits_charged = coalesce((settlement->>'creditsCharged')::integer, target_credits),
      error_code = null, error_message = null, completed_at = now(), updated_at = now()
  where request_id = job.request_id returning * into job;

  return jsonb_build_object('ok', true, 'reason', 'settled', 'status', job.status,
    'creditsEstimated', job.credits_reserved, 'creditsCharged', job.credits_charged,
    'providerTotalSeconds', job.provider_total_seconds,
    'providerInputSeconds', job.provider_input_seconds,
    'providerOutputSeconds', job.provider_output_seconds,
    'providerInputImageCount', job.provider_input_image_count);
end;
$$;

revoke all on function public.quote_minimax_h3_video_retail_credits(text, integer, integer, integer)
  from public, anon, authenticated;
revoke all on function public.quote_ai_image_unit_credits(text, text)
  from public, anon, authenticated;
revoke all on function public.quote_ai_video_retail_credits(text, text, integer, integer, boolean)
  from public, anon, authenticated;
revoke all on function public.reserve_ai_media_credits(uuid, text, text, uuid, text, integer, integer, integer)
  from public, anon, authenticated;
revoke all on function public.reserve_ai_video_credits(uuid, text, text, uuid, text, integer, integer, integer, boolean)
  from public, anon, authenticated;
revoke all on function public.reserve_minimax_video_credits(uuid, uuid, text, integer, integer)
  from public, anon, authenticated;
revoke all on function public.current_policy_ai_usage_credits(uuid, text, text, text, integer)
  from public, anon, authenticated;
revoke all on function public.settle_ai_video_download(uuid, text, text, bigint)
  from public, anon, authenticated;
grant execute on function public.quote_minimax_h3_video_retail_credits(text, integer, integer, integer) to service_role;
grant execute on function public.quote_ai_image_unit_credits(text, text) to service_role;
grant execute on function public.quote_ai_video_retail_credits(text, text, integer, integer, boolean) to service_role;
grant execute on function public.reserve_ai_media_credits(uuid, text, text, uuid, text, integer, integer, integer) to service_role;
grant execute on function public.reserve_ai_video_credits(uuid, text, text, uuid, text, integer, integer, integer, boolean) to service_role;
grant execute on function public.reserve_minimax_video_credits(uuid, uuid, text, integer, integer) to service_role;
grant execute on function public.current_policy_ai_usage_credits(uuid, text, text, text, integer) to service_role;
grant execute on function public.settle_ai_video_download(uuid, text, text, bigint) to service_role;

notify pgrst, 'reload schema';
